MERGE INTO MTX_DAILY_CONSUMPTION_FI AS DC 

USING(SELECT A.PLANT_CODE, A.WORK_CENTER, B.PRODUCT_CODE, '1000'
    CLOSING_ITEM_CODE, A.CLOSING_DATE, B.MATERIAL_CODE, 'BOM'
    INPUT_TYPE, DBO.FN_GET_INPUT_SLOC(A.PLANT_CODE, B.MATERIAL_CODE) SLOC_CODE, NULL COST_CENTER,
    DBO.FN_CHANGE_QTY_UNIT((SUM(B.BOM_QTY) / SUM(b.BASIS_QTY) * SUM(A.MODIFY_QTY)), B.BOM_QTY_UNIT, D.QTY_UNIT) AS RAW_QTY,
    DBO.FN_CHANGE_QTY_UNIT((SUM(B.BOM_QTY) / SUM(b.BASIS_QTY) * SUM(A.MODIFY_QTY)), B.BOM_QTY_UNIT, D.QTY_UNIT) AS MODIFY_QTY, D.QTY_UNIT QTY_UNIT, A.BATCH_NO PRODUCTION_BATCH_NO, A.PRODUCTION_SEQ_NO, MAX(A.ERP_FLAG) ERP_FLAG,
    ROW_NUMBER() OVER(ORDER BY A.PRODUCTION_SEQ_NO DESC) AS NUM FROM MTX_DAILY_PRODUCTION_FI A WITH(NOLOCK) JOIN MST_ERP_BOM B WITH(NOLOCK) ON A.PLANT_CODE=B.PLANT_CODE AND A.PRODUCT_CODE=B.PRODUCT_CODE AND B.ALT_BOM=(SELECT Z.ALT_BOM FROM MST_PRODUCTION_VERSION Z WHERE Z.PLANT_CODE=A.PLANT_CODE AND Z.MATERIAL_CODE=A.PRODUCT_CODE AND Z.PRODUCTION_VERSION=A.PRODUCT_VERSION) JOIN VW_MATERIAL_MASTER D WITH(NOLOCK) ON B.PLANT_CODE=D.PLANT_CODE AND B.MATERIAL_CODE=D.MATERIAL_CODE LEFT JOIN MST_MATERIAL_DAILY F ON A.PLANT_CODE=F.PLANT_CODE AND B.MATERIAL_CODE=F.MATERIAL_CODE WHERE A.CLOSING_ITEM_CODE=@P0 AND A.CLOSING_DATE=REPLACE(@P1, '-', '') AND A.PLANT_CODE=@P2 AND A.WORK_CENTER IN(SELECT Z.WORK_CENTER FROM MST_WORK_CENTER Z WHERE Z.PLANT_CODE=@P3 AND Z.PROCESS_CODE=@P4) AND ISNULL(F.APPLY_DATE, '99999999') > A.CLOSING_DATE GROUP BY A.PLANT_CODE, A.WORK_CENTER, B.PRODUCT_CODE, A.CLOSING_DATE,
    B.MATERIAL_CODE, B.SLOC_CODE, B.BOM_QTY_UNIT, D.QTY_UNIT, D.MATERIAL_TYPE, A.BATCH_NO, A.PRODUCTION_SEQ_NO) AS DP 
ON DC.PLANT_CODE=DP.PLANT_CODE 
AND DC.PRODUCTION_SEQ_NO=DP.PRODUCTION_SEQ_NO 
AND DC.WORK_CENTER=DP.WORK_CENTER 
AND DC.PRODUCT_CODE=DP.PRODUCT_CODE 
AND DC.CLOSING_ITEM_CODE=DP.CLOSING_ITEM_CODE 
AND DC.CLOSING_DATE=DP.CLOSING_DATE 
AND DC.MATERIAL_CODE=DP.MATERIAL_CODE 
AND DC.PRODUCTION_SEQ_NO=DP.PRODUCTION_SEQ_NO 
AND DC.USE_YN='Y'
WHEN MATCHED THEN UPDATE SET RAW_QTY=ROUND(DP.RAW_QTY, 3),
MODIFY_QTY=ROUND(DP.MODIFY_QTY, 3),
MODIFIER=@P5,
MODIFY_TIME=GETDATE(),
ERP_FLAG=DP.ERP_FLAG 
WHEN NOT MATCHED THEN INSERT(PLANT_CODE, WORK_CENTER, PRODUCT_CODE,
    CLOSING_ITEM_CODE, CLOSING_DATE, MATERIAL_CODE, INPUT_TYPE, SLOC_CODE